from pipeline.model_manager.models.roberta_lstm import SentimentModelWithLSTM
from pipeline.model_manager.models.roberta_linear import SentimentModelWithLinear
from pipeline.model_manager.models.bloom import SentimentModelWithBloom
from pipeline.model_manager.config import LORA_TARGET_MODULES, LORA_TASK_TYPE