PRETRAINED_PATH="PRETRAINED_PATH"
TRAINING_DATASET_PATH="TRAINING_DATASET_PATH"
OUTPUT_DIR="OUTPUT_DIR"

USE_LORA="USE_LORA"
LORA_DROPOUT="LORA_DROPOUT"
LORA_RANK="LORA_RANK"
LORA_ALPHA="LORA_ALPHA"

OPENAI_KEY="OPENAI_KEY"
DEPLOYED_MODEL_URL="DEPLOYED_MODEL_URL"
OPENAI_URL="OPENAI_URL"

LOG_FILE="LOG_FILE"
LOG_FOLDER="LOG_FOLDER"